GENERAL:
  time_step:
    value: 0.001
    constraint: [0.0001, 1]

  gravity:
    value: 9.81
    constraint: [0, 100]

  elasticity:
    value: 0.1
    constraint: [0, 1]

  xsize:
    value: 10
    constraint: [0, 11]

  ysize:
    value: 10
    constraint: [0, 11]

  zsize:
    value: 10
    constraint: [0, 11]

SIMOBJECTS:
  SIMOBJECT1:
    mass:
      value: 2.0
      constraint: [0.01, 10]

    radius:
      value: 0.5
      constraint: [0.01, 20]
  
    color: red

    motion_vector:
      value: [-50, -50, -50]
      constraint: [-100, 100]

    position_vector:
      value: [9, 9, 9]
      constraint: [0, 10]

  SIMOBJECT2:
    mass:
      value: 3.0
      constraint: [0.01, 10]

    radius:
      value: 0.5
      constraint: [0.01, 20]

    color: blue

    motion_vector:
      value: [50, 50, 50]
      constraint: [-100, 100]

    position_vector:
      value: [1, 1, 1]
      constraint: [0, 10]


  SIMOBJECT3:
    mass:
      value: 3.0
      constraint: [0.01, 10]

    radius:
      value: 0.5
      constraint: [0.01, 20]

    color: blue

    motion_vector:
      value: [50, 50, 50]
      constraint: [-100, 100]

    position_vector:
      value: [3, 2, 1]
      constraint: [0, 10]

  SIMOBJECT4:
    mass:
      value: 9.0
      constraint: [0.01, 10]

    radius:
      value: 2
      constraint: [0.01, 20]

    color: blue

    motion_vector:
      value: [50, 50, 50]
      constraint: [-100, 100]

    position_vector:
      value: [7, 7, 7]
      constraint: [0, 10]