GENERAL:
  time_step: 0.001 # [0.01 - 0.0001]
  restitution: 1 # [0 - 1]
  size: 10 # [10-100]


SIMOBJECTS:
  SIMOBJECT1:
    type: sphere # [sphere, cube]
    mass: 10 # > 0
    radius: 1 # > 0, sollte nicht mit andern Objekten oder den Wänden überlappen
    color: blue # [red, green, blue, yellow, cyan, magenta, black, white, gray, orange, purple]
    motion_vector: [-50, -40, -50] # [-1000 - 1000] für jede Komponente
    position_vector: [-2, 2, -7] # Objekt sollte innerhalb der Simulation und ohne andere Objekte zu schneiden platziert sein

  # Würfelobjekte besitzen weniger Attribute als Kugeln
  SIMOBJECT2:
    type: cube
    color: white
    sidelength: 2 # Würfel sollte so dimensioniert und platziert sein, dass er keine anderen Objekte schneidet/enthält
    position_vector: [5, 5, 5]

  SIMOBJECT3:
    type: sphere
    mass: 50
    radius: 1
    color: orange
    motion_vector: [50, 50, 50]
    position_vector: [3, 3, 3]

  SIMOBJECT4:
    type: sphere
    mass: 3
    radius: 1
    color: red
    motion_vector: [50, 30, 20]
    position_vector: [6, 4, 4]

  SIMOBJECT5:
    type: sphere
    mass: 5
    radius: 1
    color: green
    motion_vector: [50, 50, 50]
    position_vector: [7, 0, 7]